#!/bin/bash

# allow tcp ports
iptables -D INPUT -p tcp --dport 22 -j ACCEPT
iptables -D INPUT -p tcp --dport 80 -j ACCEPT
iptables -D INPUT -p tcp --dport 443 -j ACCEPT
iptables -D INPUT -p tcp --dport 587 -j ACCEPT
iptables -D INPUT -p tcp --dport 993 -j ACCEPT
iptables -D INPUT -p tcp --dport 22345 -j ACCEPT

# allow tcp & udp on 53
iptables -D INPUT -p tcp --dport 53 -j ACCEPT
iptables -D INPUT -p udp --dport 53 -j ACCEPT

# allow icmp echo-request
iptables -D INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -D OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

# allow everything from IP addresses
iptables -D INPUT -s 10.0.0.0/8 -j ACCEPT
iptables -D INPUT -s 192.168.255.0/24 -j ACCEPT
iptables -D INPUT -s 172.16.0.0/16 -j ACCEPT
iptables -D INPUT -s 193.191.177.6 -j ACCEPT  # mrt.uclllabs.be
iptables -D INPUT -s 193.191.177.1 -j ACCEPT  # leia.uclllabs.be

# disable ip routing
iptables -D FORWARD -j DROP

# set default policy to drop the rest
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

iptables -D INPUT -i lo -j ACCEPT
iptables -D OUTPUT -o lo -j ACCEPT

# enable tcp syn cookies
awk -i inplace '/net.ipv4.tcp_syncookies/ { gsub("net.ipv4.tcp_syncookies=1", "#net.ipv4.tcp_syncookies=1") }1' /etc/sysctl.conf
sysctl -p

# save iptables
iptables-save > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6
