#!/bin/bash

# allow tcp ports
#iptables -A INPUT -p tcp --dport 22 -j ACCEPT
#iptables -A INPUT -p tcp --dport 80 -j ACCEPT
#iptables -A INPUT -p tcp --dport 443 -j ACCEPT
#iptables -A INPUT -p tcp --dport 587 -j ACCEPT
#iptables -A INPUT -p tcp --dport 993 -j ACCEPT
#iptables -A INPUT -p tcp --dport 22345 -j ACCEPT

# allow tcp & udp on 53
#iptables -A INPUT -p tcp --sport 53 -j ACCEPT
#iptables -A INPUT -p udp --sport 53 -j ACCEPT

# allow icmp echo-request
#iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
#iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

# allow everything from IP addresses
#iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
#iptables -A INPUT -s 192.168.255.0/24 -j ACCEPT
#iptables -A INPUT -s 172.16.0.0/16 -j ACCEPT
#iptables -A INPUT -s 193.191.177.6 -j ACCEPT  # mrt.uclllabs.be
#iptables -A INPUT -s 193.191.177.1 -j ACCEPT  # leia.uclllabs.be

# allow git
#iptables -A INPUT -p tcp --sport 9418 -j ACCEPT

# disable ip routing
#iptables -I FORWARD -j DROP

# set default policy to drop the rest
#iptables -P INPUT DROP
#iptables -P FORWARD DROP
#iptables -P OUTPUT ACCEPT

#iptables -I INPUT -i lo -j ACCEPT
#iptables -I OUTPUT -o lo -j ACCEPT

# enable tcp syn cookies
awk -i inplace '/#net.ipv4.tcp_syncookies/ { gsub("#", "") }1' /etc/sysctl.conf
sysctl -p

# save iptables
#iptables-save > /etc/iptables/rules.v4
#ip6tables-save > /etc/iptables/rules.v6

# load firewall rules from files
iptables-restore < /etc/iptables/firewall-rules.v4
ip6tables-restore < /etc/iptables/firewall-rules.v6

