#!/bin/bash

# check argument
if [ "$#" -ne "1" ]
then
	echo "http_add_vhost takes 1 argument: fully_qualified_domain_name"
	exit 1
fi

# add virtual host file for the domain
echo "<VirtualHost *:80>
        ServerName $1
        DocumentRoot /var/www/html/$1

	LogLevel info
        ErrorLog \${APACHE_LOG_DIR}/$1-error.log
        CustomLog \${APACHE_LOG_DIR}/$1-access.log combined
	</VirtualHost>
	" > /etc/apache2/sites-available/$1

# create a default index page
